[global]

[logger]
level = "info"
messageFormat = "%(asctime)s	%(levelname)s	%(name)s	%(message)s"

[client]
showErrorDetails = "full"

[runner]

[server]
port = 8502
maxUploadSize = 1
fileWatcherType = "none"
baseUrlPath = "/de-dorf"

[browser]
gatherUsageStats = false

[mapbox]

[theme]
base = "dark"

[secrets]
