[global]

[logger]
level = "info"
messageFormat = "%(asctime)s	%(levelname)s	%(name)s	%(message)s"

[client]
showErrorDetails = "full"

[runner]

[server]
baseUrlPath = "/de-dorf"
fileWatcherType = "none"
maxUploadSize = 1
port = 8502

[browser]
gatherUsageStats = false

[mapbox]

[theme]
base = "dark"

[secrets]
